/**
 * `nuxt-backend billing sync` — push the code-declared catalog
 * (`backend/billing.catalog.ts`) to the billing provider and write the id map
 * to `backend/billing.generated.ts`.
 *
 * Find-or-create only: every managed object is tagged
 * `metadata: { managedBy: 'nuxt-backend', key }` and looked up by that tag on
 * the next run, so re-running is idempotent. Nothing remote is ever updated
 * (prices on subscribed products are a dashboard task) or deleted — managed
 * objects whose key left the catalog are reported as drift. Granting stays
 * provider-native: plan/pack credits become meter-credit benefits attached to
 * the products, granted by the provider per cycle / at purchase.
 *
 * `--adopt key=<id>` records an existing product/meter under a catalog key
 * instead of creating a managed twin — benefits of adopted products are left
 * exactly as they are.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { defineCommand } from 'citty'
import { Polar } from '@polar-sh/sdk'
import { metersCreate } from '@polar-sh/sdk/funcs/metersCreate.js'
import { metersList } from '@polar-sh/sdk/funcs/metersList.js'
import { benefitsCreate } from '@polar-sh/sdk/funcs/benefitsCreate.js'
import { benefitsList } from '@polar-sh/sdk/funcs/benefitsList.js'
import { productsCreate } from '@polar-sh/sdk/funcs/productsCreate.js'
import { productsList } from '@polar-sh/sdk/funcs/productsList.js'
import { productsUpdateBenefits } from '@polar-sh/sdk/funcs/productsUpdateBenefits.js'
import { webhooksCreateWebhookEndpoint } from '@polar-sh/sdk/funcs/webhooksCreateWebhookEndpoint.js'
import { webhooksListWebhookEndpoints } from '@polar-sh/sdk/funcs/webhooksListWebhookEndpoints.js'
import type { BillingCatalog, CatalogCreditGrant } from '../convex/catalog'
import { BILLING_WEBHOOK_PROVISION_EVENTS } from '../convex/catalog'
import { resolveFunctionsDir } from '../scaffold'
import { readEnvFiles } from '../env-push'
import { deriveDeploymentUrls } from '../deployment'

const MANAGED_BY = 'nuxt-backend'

type Environment = 'sandbox' | 'production'

interface CreditMeterIds {
  meterId: string
  eventName?: string
  property?: string
}

interface CatalogIds {
  products: Record<string, string>
  meters: Record<string, CreditMeterIds>
}

interface SyncLogEntry {
  action: 'created' | 'exists' | 'adopted' | 'would-create' | 'drift' | 'warn'
  kind: 'meter' | 'benefit' | 'product' | 'webhook'
  key: string
  id?: string
  note?: string
}

function isManaged(metadata: Record<string, unknown> | undefined | null, key: string): boolean {
  return metadata?.managedBy === MANAGED_BY && metadata?.key === key
}

/** Load the app's `billing.catalog.ts` via native TS import. */
async function loadCatalog(rootDir: string): Promise<{ catalog: BillingCatalog, path: string } | null> {
  const functionsDir = resolveFunctionsDir(rootDir)
  const path = join(rootDir, functionsDir, 'billing.catalog.ts')
  if (!existsSync(path)) return null
  const module = await import(pathToFileURL(path).href) as { default?: BillingCatalog }
  return { catalog: module.default ?? {}, path }
}

/** Load the existing generated map (to preserve the other environment). */
async function loadGenerated(rootDir: string): Promise<Partial<Record<Environment, CatalogIds>>> {
  const functionsDir = resolveFunctionsDir(rootDir)
  const path = join(rootDir, functionsDir, 'billing.generated.ts')
  if (!existsSync(path)) return {}
  try {
    // Cache-bust: the file is rewritten between runs in one process (tests).
    const module = await import(`${pathToFileURL(path).href}?t=${Date.now()}`) as { catalog?: Partial<Record<Environment, CatalogIds>> }
    return module.catalog ?? {}
  }
  catch {
    return {}
  }
}

function renderGenerated(map: Partial<Record<Environment, CatalogIds>>): string {
  return `/* Generated by \`npx nuxt-backend billing sync\` — do not edit. */
import type { BillingCatalogIds } from 'nuxt-backend/billing'

export const catalog: Partial<Record<'sandbox' | 'production', BillingCatalogIds>> = ${JSON.stringify(map, null, 2)}
`
}

export interface BillingSyncOptions {
  rootDir: string
  environment: Environment
  accessToken: string
  dryRun: boolean
  /** Adopt existing provider objects: catalog key → provider id. */
  adopt: Record<string, string>
  /** Webhook endpoint URL to provision (skipped when absent). */
  webhookUrl?: string
}

export interface BillingSyncResult {
  log: SyncLogEntry[]
  ids: CatalogIds
  webhookSecret?: string
}

/** The whole provider reconciliation. Exported for tests (client injectable). */
export async function syncBillingCatalog(
  catalog: BillingCatalog,
  options: BillingSyncOptions,
  client: Polar = new Polar({ accessToken: options.accessToken, server: options.environment }),
): Promise<BillingSyncResult> {
  const log: SyncLogEntry[] = []
  const ids: CatalogIds = { products: {}, meters: {} }
  const { dryRun, adopt } = options

  // --- Managed inventories (one list call per kind, metadata-filtered) ---
  const managedMeters = await listAllPages(page => metersList(client, { metadata: { managedBy: MANAGED_BY }, limit: 100, page }))
  const managedBenefits = await listAllPages(page => benefitsList(client, { limit: 100, page }))
  const managedProducts = await listAllPages(page => productsList(client, { metadata: { managedBy: MANAGED_BY }, limit: 100, page }))

  // --- Meters ---
  for (const [key, meter] of Object.entries(catalog.meters ?? {})) {
    const aggregation = meter.aggregation ?? 'sum'
    const property = aggregation === 'sum' ? meter.property ?? 'amount' : undefined
    const eventName = meter.eventName ?? key
    const record = (meterId: string) => {
      ids.meters[key] = { meterId, eventName, ...(property ? { property } : {}) }
    }
    if (adopt[key]) {
      record(adopt[key])
      log.push({ action: 'adopted', kind: 'meter', key, id: adopt[key] })
      continue
    }
    const existing = managedMeters.find(item => isManaged(item.metadata, key))
    if (existing) {
      record(existing.id)
      log.push({ action: 'exists', kind: 'meter', key, id: existing.id })
      continue
    }
    if (dryRun) {
      log.push({ action: 'would-create', kind: 'meter', key })
      continue
    }
    const created = await metersCreate(client, {
      name: key,
      filter: { conjunction: 'and', clauses: [{ property: 'name', operator: 'eq', value: eventName }] },
      aggregation: property ? { func: 'sum', property } : { func: 'count' },
      metadata: { managedBy: MANAGED_BY, key },
    })
    if (!created.ok) throw created.error
    record(created.value.id)
    log.push({ action: 'created', kind: 'meter', key, id: created.value.id })
  }

  // --- Benefits (feature benefits + per-product credit grants) ---
  const benefitIdByKey = new Map<string, string>()
  const ensureBenefit = async (key: string, create: () => Parameters<typeof benefitsCreate>[1]): Promise<string | null> => {
    const existing = managedBenefits.find(item => isManaged((item as { metadata?: Record<string, unknown> }).metadata, key))
    if (existing) {
      benefitIdByKey.set(key, existing.id)
      log.push({ action: 'exists', kind: 'benefit', key, id: existing.id })
      return existing.id
    }
    if (dryRun) {
      log.push({ action: 'would-create', kind: 'benefit', key })
      return null
    }
    const created = await benefitsCreate(client, create())
    if (!created.ok) throw created.error
    benefitIdByKey.set(key, created.value.id)
    log.push({ action: 'created', kind: 'benefit', key, id: created.value.id })
    return created.value.id
  }

  for (const [key, feature] of Object.entries(catalog.features ?? {})) {
    await ensureBenefit(key, () => ({
      type: 'custom',
      description: feature.description,
      properties: { note: null },
      // `key` doubles as the friendly gate name `useFeatures().has(key)` matches.
      metadata: { managedBy: MANAGED_BY, key },
    }))
  }

  const creditBenefitFor = async (productKey: string, grant: CatalogCreditGrant, defaultRollover: boolean): Promise<string | null> => {
    const meterIds = ids.meters[grant.meter]
    if (!meterIds) {
      log.push({ action: 'warn', kind: 'benefit', key: `${productKey}-credits`, note: `meter '${grant.meter}' is not in the catalog` })
      return null
    }
    return ensureBenefit(`${productKey}-credits`, () => ({
      type: 'meter_credit',
      description: `${grant.units} credits`,
      properties: { units: grant.units, rollover: grant.rollover ?? defaultRollover, meterId: meterIds.meterId },
      metadata: { managedBy: MANAGED_BY, key: `${productKey}-credits` },
    }))
  }

  // --- Products (plans + packs) ---
  const ensureProduct = async (
    key: string,
    benefits: Array<string | null>,
    create: () => Parameters<typeof productsCreate>[1],
  ): Promise<void> => {
    if (adopt[key]) {
      // Adopted products keep their existing benefits untouched — creating
      // managed grant twins would double-grant.
      ids.products[key] = adopt[key]
      log.push({ action: 'adopted', kind: 'product', key, id: adopt[key], note: 'benefits left as-is' })
      return
    }
    const existing = managedProducts.find(item => isManaged(item.metadata, key))
    if (existing) {
      ids.products[key] = existing.id
      log.push({ action: 'exists', kind: 'product', key, id: existing.id })
      return
    }
    if (dryRun) {
      log.push({ action: 'would-create', kind: 'product', key })
      return
    }
    const created = await productsCreate(client, create())
    if (!created.ok) throw created.error
    ids.products[key] = created.value.id
    log.push({ action: 'created', kind: 'product', key, id: created.value.id })
    const attach = benefits.filter((id): id is string => id !== null)
    if (attach.length > 0) {
      const updated = await productsUpdateBenefits(client, { id: created.value.id, productBenefitsUpdate: { benefits: attach } })
      if (!updated.ok) throw updated.error
    }
  }

  for (const [key, plan] of Object.entries(catalog.plans ?? {})) {
    const benefits: Array<string | null> = []
    // Plan allowances default to use-it-or-lose-it per cycle.
    if (plan.credits) benefits.push(await creditBenefitFor(key, plan.credits, false))
    for (const featureKey of plan.features ?? []) {
      const id = benefitIdByKey.get(featureKey)
      if (id) benefits.push(id)
      else if (!dryRun) log.push({ action: 'warn', kind: 'product', key, note: `feature '${featureKey}' is not in the catalog` })
    }
    await ensureProduct(key, benefits, () => ({
      name: plan.name,
      description: plan.description,
      recurringInterval: plan.interval,
      prices: [{ amountType: 'fixed', priceAmount: plan.price }],
      metadata: { managedBy: MANAGED_BY, key },
    }))
  }

  for (const [key, pack] of Object.entries(catalog.packs ?? {})) {
    // Purchased credits keep by default (rollover).
    const benefit = await creditBenefitFor(key, pack.credits, true)
    await ensureProduct(key, [benefit], () => ({
      name: pack.name,
      description: pack.description,
      recurringInterval: null,
      prices: [{ amountType: 'fixed', priceAmount: pack.price }],
      metadata: { managedBy: MANAGED_BY, key },
    }))
  }

  // --- Drift: managed remote objects whose key left the catalog ---
  const knownKeys = new Set([
    ...Object.keys(catalog.meters ?? {}),
    ...Object.keys(catalog.plans ?? {}),
    ...Object.keys(catalog.packs ?? {}),
    ...Object.keys(catalog.features ?? {}),
    ...[...Object.keys(catalog.plans ?? {}), ...Object.keys(catalog.packs ?? {})].map(key => `${key}-credits`),
  ])
  for (const [kind, items] of [['meter', managedMeters], ['product', managedProducts], ['benefit', managedBenefits]] as const) {
    for (const item of items) {
      const metadata = (item as { metadata?: Record<string, unknown> }).metadata
      if (metadata?.managedBy !== MANAGED_BY) continue
      const key = typeof metadata.key === 'string' ? metadata.key : ''
      if (key && !knownKeys.has(key)) {
        log.push({ action: 'drift', kind, key, id: item.id, note: 'managed remotely but no longer in the catalog (never deleted automatically)' })
      }
    }
  }

  // --- Webhook endpoint ---
  let webhookSecret: string | undefined
  if (options.webhookUrl) {
    const endpoints = await listAllPages(page => webhooksListWebhookEndpoints(client, { limit: 100, page }))
    const existing = endpoints.find(endpoint => endpoint.url === options.webhookUrl)
    if (existing) {
      log.push({ action: 'exists', kind: 'webhook', key: options.webhookUrl, id: existing.id })
    }
    else if (dryRun) {
      log.push({ action: 'would-create', kind: 'webhook', key: options.webhookUrl })
    }
    else {
      const created = await webhooksCreateWebhookEndpoint(client, {
        url: options.webhookUrl,
        format: 'raw',
        events: [...BILLING_WEBHOOK_PROVISION_EVENTS],
      })
      if (!created.ok) throw created.error
      webhookSecret = created.value.secret
      log.push({ action: 'created', kind: 'webhook', key: options.webhookUrl, id: created.value.id })
    }
  }

  return { log, ids, webhookSecret }
}

/** Drain a paginated list endpoint (`{ result: { items, pagination } }`). */
async function listAllPages<T extends { id: string, metadata?: unknown }>(
  fetchPage: (page: number) => Promise<{ ok: boolean, error?: unknown, value?: { result: { items: T[], pagination: { maxPage: number } } } }>,
): Promise<T[]> {
  const items: T[] = []
  for (let page = 1; ; page++) {
    const result = await fetchPage(page)
    if (!result.ok || !result.value) throw result.error ?? new Error('[nuxt-backend] billing sync: list request failed')
    items.push(...result.value.result.items)
    if (page >= result.value.result.pagination.maxPage) break
  }
  return items
}

export const billingSync = defineCommand({
  meta: { name: 'sync', description: 'Push backend/billing.catalog.ts to the billing provider and write billing.generated.ts (find-or-create, never deletes)' },
  args: {
    'cwd': { type: 'string', description: 'Project directory', default: '.' },
    'env': { type: 'string', description: 'Target environment: sandbox | production (default: BILLING_ENVIRONMENT or sandbox)' },
    'dry-run': { type: 'boolean', description: 'Print the plan without creating anything', default: false },
    'webhook': { type: 'string', description: 'Provision the webhook endpoint at this URL (default: derived <site>/billing/events; pass "off" to skip)' },
    'adopt': { type: 'string', description: 'Adopt existing objects: key=<id>[,key=<id>…] — recorded as-is, benefits untouched' },
  },
  async run({ args }) {
    const rootDir = resolve(process.cwd(), args.cwd)
    const localEnv = readEnvFiles(rootDir)
    const environment = (args.env ?? process.env.BILLING_ENVIRONMENT ?? localEnv.BILLING_ENVIRONMENT ?? 'sandbox') as Environment
    if (environment !== 'sandbox' && environment !== 'production') {
      console.error(`[nuxt-backend] Unknown billing environment '${environment}' — use sandbox or production.`)
      process.exitCode = 1
      return
    }
    const accessToken = process.env.BILLING_ACCESS_TOKEN ?? localEnv.BILLING_ACCESS_TOKEN
    if (!accessToken) {
      console.error('[nuxt-backend] BILLING_ACCESS_TOKEN is not set (env or .env.local) — create an organization access token in the provider dashboard.')
      process.exitCode = 1
      return
    }

    const loaded = await loadCatalog(rootDir)
    if (!loaded) {
      console.error('[nuxt-backend] No billing.catalog.ts found — run `npx nuxt-backend init` (or create backend/billing.catalog.ts) first.')
      process.exitCode = 1
      return
    }

    const adopt: Record<string, string> = {}
    for (const pair of (args.adopt ?? '').split(',').filter(Boolean)) {
      const [key, id] = pair.split('=')
      if (key && id) adopt[key.trim()] = id.trim()
    }

    const webhookUrl = args.webhook === 'off'
      ? undefined
      : args.webhook ?? (() => {
        const siteUrl = deriveDeploymentUrls(rootDir)?.siteUrl
        return siteUrl ? `${siteUrl}/billing/events` : undefined
      })()

    console.log(`[nuxt-backend] billing sync → ${environment}${args['dry-run'] ? ' — dry run' : ''}`)
    const result = await syncBillingCatalog(loaded.catalog, {
      rootDir,
      environment,
      accessToken,
      dryRun: args['dry-run'],
      adopt,
      webhookUrl,
    })

    for (const entry of result.log) {
      const id = entry.id ? ` (${entry.id})` : ''
      const note = entry.note ? ` — ${entry.note}` : ''
      console.log(`  ${entry.action.padEnd(12)} ${entry.kind.padEnd(8)} ${entry.key}${id}${note}`)
    }

    if (!args['dry-run']) {
      const generated = await loadGenerated(rootDir)
      generated[environment] = result.ids
      const functionsDir = resolveFunctionsDir(rootDir)
      const outPath = join(rootDir, functionsDir, 'billing.generated.ts')
      writeFileSync(outPath, renderGenerated(generated))
      console.log(`[nuxt-backend] Wrote ${outPath}`)
    }

    if (result.webhookSecret) {
      console.log('\n[nuxt-backend] Webhook endpoint created. Store its secret on the deployment:')
      console.log(`  npx convex env set BILLING_WEBHOOK_SECRET ${result.webhookSecret}`)
    }
  },
})

export const billing = defineCommand({
  meta: { name: 'billing', description: 'Billing catalog helpers' },
  subCommands: { sync: billingSync },
})
