/* Generated by `npx nuxt-backend billing sync` — do not edit. */
import type { BillingCatalogIds } from 'nuxt-backend/billing'

export const catalog: Partial<Record<'sandbox' | 'production', BillingCatalogIds>> = {
  sandbox: {
    products: {
      starter: '96561ea3-e168-4219-9716-5128ac57dd7c',
      pro: 'd852636d-a5fb-4472-b592-3ac921a84ba3',
      ultra: '9e9097b4-22dc-4b40-9823-47a15fbe9f17',
      credits100: 'f55734b4-428f-47b9-b305-70576acf9181',
      credits500: '907659da-d66c-4e4a-9cb3-799ec445c79b',
    },
    meters: {
      credits: {
        meterId: 'aa62cf4c-2dcd-437d-a407-1872f51531b7',
      },
    },
  },
}
