/* Generated by `npx nuxt-backend billing sync` — do not edit. */
import type { BillingCatalogIds } from 'nuxt-backend/billing'

export const catalog: Partial<Record<'sandbox' | 'production', BillingCatalogIds>> = {
  sandbox: {
    products: {
      starter: '7a4d2654-12ab-4ab4-84fa-cc2bafd483c0',
      pro: 'c7372c4e-2581-42d1-a514-7aec9a2a8ab6',
      ultra: 'a95df103-3f0e-461e-b260-118343396561',
      credits100: '0313cfbe-b321-4fde-873a-00e27748682f',
      credits500: '8eb269bd-5f98-4a3f-9850-ff5f44d03da7',
    },
    meters: {
      credits: {
        meterId: '8455082f-da79-4961-b323-bc799ddf7fbc',
        eventName: 'credits',
      },
    },
  },
}
