/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
// Verbatim copy of examples/minimal/backend, present so the scaffolder finds
// every default file in place. Never built or typechecked (no codegen here).
/* Generated by `npx nuxt-backend billing sync` — do not edit. */
import type { BillingCatalogIds } from 'nuxt-backend/billing'

export const catalog: Partial<Record<'sandbox' | 'production', BillingCatalogIds>> = {}
