/* Generated by `pnpm templates:generate` (scripts/generate-templates.mjs) — do not edit. */
/**
 * Top-level exports of the packaged backend component, parsed from
 * src/convex/components/backend/{ai,billing,email,gifts,webhooks,schema}.ts.
 * The local-install scaffold (src/templates.ts) re-exports exactly these names, so
 * `installation: 'local'` cannot drift from the real component —
 * test/unit/templates-generated.test.ts fails while this file is stale.
 */

/** Every value export of each function module, sorted — `nuxt-backend/component/<name>`. */
export const COMPONENT_MODULE_EXPORTS = {
  ai: [
    'clear',
    'createRequest',
    'getByStream',
    'markReleased',
    'markSettled',
  ],
  billing: [
    'attachReleaseJob',
    'clear',
    'clearPendingSpends',
    'credit',
    'debit',
    'deleteByUser',
    'finalize',
    'getBenefitMetadata',
    'getByUser',
    'release',
    'settle',
    'upsert',
    'upsertBenefitMetadata',
    'userByCustomer',
  ],
  email: [
    'cancel',
    'cleanup',
    'cleanupAbandoned',
    'get',
    'handleWebhook',
    'send',
    'status',
  ],
  gifts: [
    'create',
    'get',
    'listByEmail',
    'markClaimed',
    'markNotified',
    'markPaid',
    'resolveRecipient',
  ],
  webhooks: [
    'find',
    'listRecent',
    'record',
    'vDeliveryOutcome',
  ],
} as const

/** Every value export of the component schema, sorted — `nuxt-backend/component/schema`. */
export const SCHEMA_EXPORTS = [
  'aiTables',
  'authSchema',
  'billingTables',
  'tables',
  'vEntitlementBenefit',
  'vEntitlementMeter',
  'vGift',
  'vPendingSpend',
  'webhookTables',
] as const
