import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * `billing sync` writes `backend/billing.generated.ts` into the consumer's
 * repository, where their own linter sees it — and they must never edit it. So
 * the file it emits has to be idiomatic TypeScript (single quotes, bare keys,
 * trailing commas), not `JSON.stringify` output, which fails the default
 * `@stylistic` rules this repo and most Nuxt projects run.
 */
const root = join(import.meta.dirname, '../..')
const source = readFileSync(join(root, 'src/cli/billing.ts'), 'utf8')

describe('generated catalog file', () => {
  it('renders values as lint-clean TypeScript, not JSON', () => {
    expect(source).toContain('function renderValue(')
    // The old implementation; a regression would reintroduce it.
    expect(source).not.toContain('JSON.stringify(map, null, 2)')
  })

  it('the committed playground map matches the renderer\'s output shape', () => {
    const generated = readFileSync(join(root, 'website/backend/billing.generated.ts'), 'utf8')
    expect(generated).toContain('/* Generated by `npx nuxt-backend billing sync` — do not edit. */')
    // Bare keys, single quotes, trailing commas — the three things JSON gets wrong.
    expect(generated).toMatch(/^ {2}sandbox: \{$/m)
    expect(generated).not.toMatch(/"[a-z]/i)
    expect(generated).toMatch(/',\n/)
  })
})
